# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.2
#  - nightly
branches:
  only:
  - master
notifications:
  email: false

after_success:
  # push coverage results to Coveralls
  - julia -e 'using SegyIO; cd(dirname(dirname(pathof(SegyIO)))); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using SegyIO; cd(dirname(dirname(pathof(SegyIO)))); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
