# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false

after_success:
  # push coverage results to Coveralls
  - julia -e 'using SeisIO; cd(dirname(dirname(pathof(SeisIO)))); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using SeisIO; cd(dirname(dirname(pathof(SeisIO)))); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
