name: CI-tests

on: [push]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        version:
          - '1.0'
          - '1.1'
          - '1.2'
          - '1.3'
          - 'nightly'
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - x64

    steps:
      - name: Checkout JUDI
        uses: actions/checkout@v2

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Run tests
	    uses: julia-actions/julia-runtest@master
